---
- name: Preparation
  hosts: traffic
  become: yes
  become_user: root
  tasks: 
    - name: Start JBOSS Traffic
      systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - ss7ec
        - DP-NGIN-JBOSS-Traffic
        
- name: Preparation
  hosts: frontend
  become: yes
  become_user: root
  tasks: 
    - name: Start JBOSS BM
      systemd:
        name: DP-NGIN-JBOSS-BM
        state: started
        
- name: Preparation
  hosts: ece
  become: yes
  become_user: root
  tasks: 
    - name: Start statistics & rda
      systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - aggregateStatistics.service
        - rda.consul-template 
        - esa.service
